name: Update Submodules

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update submodules
        run: |
          git submodule update --remote --recursive

      - name: Commit updated submodules
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: update submodules to latest commit" || echo "No changes to commit"
          git push
